[build]
  publish = "."

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = false

[context.production]
  publish = "."

[context.branch-deploy]
  publish = "."

[context.deploy-preview]
  publish = "."
